# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 13:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['sequence']},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='label',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default=datetime.datetime(2016, 7, 19, 13, 50, 12, 954777, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.Category'),
        ),
    ]
